import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import Ticket from "@/components/Ticket";
import { TicketSkeleton } from "@/components/TicketSkeleton";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useAuth } from "@/hooks/useAuth";
import { useUserTickets } from "@/hooks/useTickets";
import { useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
function MyTicketsPage() {
    const { user } = useAuth();
    const { tickets, isLoading, error } = useUserTickets(user?.uid);
    const queryClient = useQueryClient();
    const refetch = () => {
        queryClient.invalidateQueries({ queryKey: ["userTickets", user?.uid] });
    };
    if (isLoading) {
        return (_jsx("div", { className: "min-h-screen gradient-bg transition-colors", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: [_jsxs("div", { className: "text-center mb-8 space-y-4", children: [_jsx(Skeleton, { className: "h-16 w-16 rounded-full mx-auto" }), _jsx(Skeleton, { className: "h-10 w-64 mx-auto" })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [...Array(3)].map((_, i) => (_jsx(TicketSkeleton, {}, i))) })] }) }));
    }
    return (_jsx("div", { className: "min-h-screen gradient-bg transition-colors", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8", children: [_jsxs("div", { className: "text-center mb-8", children: [_jsx("h1", { className: "text-4xl font-bold text-foreground mb-2", children: "Meus Ingressos" }), _jsxs("p", { className: "text-xl text-muted-foreground", children: ["Bem-vindo,", " ", _jsx("span", { className: "font-semibold text-primary", children: user?.email }), "!"] })] }), error && (_jsxs("div", { className: "card max-w-md mx-auto text-center mb-8 bg-background", children: [_jsx("h3", { className: "text-xl font-bold text-red-600 dark:text-red-400 mb-2", children: "Erro ao carregar ingressos" }), _jsx("p", { className: "text-muted-foreground mb-4", children: error.message }), _jsx(Button, { onClick: refetch, children: "Tentar Novamente" })] })), !error && tickets && (_jsx(_Fragment, { children: tickets.length === 0 ? (
                    /* Empty State */
                    _jsxs("div", { className: "card max-w-lg mx-auto text-center bg-white dark:bg-gray-800", children: [_jsx("h2", { className: "text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4", children: "Voc\u00EA ainda n\u00E3o possui ingressos" }), _jsx("p", { className: "text-gray-600 dark:text-gray-400 mb-8", children: "Que tal explorar nossos eventos incr\u00EDveis e garantir seu lugar?" }), _jsx(Button, { asChild: true, className: "text-lg px-8 py-3", children: _jsx(Link, { to: "/eventos", children: "Descobrir Eventos" }) })] })) : (_jsxs("div", { className: "space-y-8", children: [_jsxs("div", { className: "flex flex-col md:flex-row items-center justify-between gap-4 bg-card p-4 rounded-lg shadow-sm border", children: [_jsxs("h2", { className: "text-2xl font-bold text-foreground", children: ["Seus Ingressos (", tickets.length, ")"] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("div", { className: "flex items-center text-sm text-muted-foreground bg-green-100 dark:bg-green-900/20 px-3 py-1 rounded-full", children: [_jsx("div", { className: "w-2 h-2 bg-green-500 rounded-full mr-2" }), "V\u00E1lido"] }), _jsxs("div", { className: "flex items-center text-sm text-muted-foreground bg-red-100 dark:bg-red-900/20 px-3 py-1 rounded-full", children: [_jsx("div", { className: "w-2 h-2 bg-red-500 rounded-full mr-2" }), "Usado"] })] })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: tickets.map((ticket) => (_jsx("div", { className: "h-full", children: _jsx(Ticket, { ticket: ticket }) }, ticket.id))) }), _jsxs("div", { className: "card bg-gradient-to-r from-primary to-accent text-primary-foreground text-center mt-12", children: [_jsx("h3", { className: "text-xl font-bold mb-4", children: "A\u00E7\u00F5es R\u00E1pidas" }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsxs(Link, { to: "/eventos", className: "bg-white/20 hover:bg-white/30 dark:bg-black/20 dark:hover:bg-black/30 rounded-lg p-4 text-center transition-colors backdrop-blur-sm", children: [_jsx("div", { className: "font-semibold", children: "Explorar Eventos" }), _jsx("div", { className: "text-sm opacity-90", children: "Descubra novos eventos" })] }), _jsxs(Link, { to: "/perfil", className: "bg-white/20 hover:bg-white/30 dark:bg-black/20 dark:hover:bg-black/30 rounded-lg p-4 text-center transition-colors backdrop-blur-sm", children: [_jsx("div", { className: "font-semibold", children: "Meu Perfil" }), _jsx("div", { className: "text-sm opacity-90", children: "Gerenciar conta" })] })] })] })] })) }))] }) }));
}
export default MyTicketsPage;
