import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "../ui/button";
export function ValidationResult({ status, message, ticketData, onConfirm, }) {
    if (status === null) {
        return (_jsxs("div", { className: "text-center py-12 text-gray-500 dark:text-gray-400", children: [_jsx("div", { className: "text-6xl mb-4", children: "\u23F3" }), _jsx("p", { children: "Digite um c\u00F3digo de ingresso para validar" })] }));
    }
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "text-center", children: [status === "success" && (_jsxs("div", { className: "inline-flex items-center px-4 py-2 bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 rounded-none", children: [_jsx("span", { className: "mr-2", children: "\u2705" }), _jsx("span", { className: "font-semibold", children: "V\u00C1LIDO" })] })), status === "error" && (_jsxs("div", { className: "inline-flex items-center px-4 py-2 bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 rounded-none", children: [_jsx("span", { className: "mr-2", children: "\u274C" }), _jsx("span", { className: "font-semibold", children: "USADO" })] })), status === "invalid" && (_jsxs("div", { className: "inline-flex items-center px-4 py-2 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-800 dark:text-yellow-300 rounded-none", children: [_jsx("span", { className: "mr-2", children: "\u26A0\uFE0F" }), _jsx("span", { className: "font-semibold", children: "INV\u00C1LIDO" })] }))] }), _jsx("div", { className: `p-4 rounded-none text-center ${status === "success"
                    ? "bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800"
                    : status === "error"
                        ? "bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800"
                        : "bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800"}`, children: _jsx("p", { className: `font-medium ${status === "success"
                        ? "text-green-800 dark:text-green-300"
                        : status === "error"
                            ? "text-red-800 dark:text-red-300"
                            : "text-yellow-800 dark:text-yellow-300"}`, children: message }) }), status === "success" && ticketData && (_jsxs("div", { className: "bg-gray-50 dark:bg-gray-800/50 rounded-none p-4 space-y-3", children: [_jsx("h4", { className: "font-semibold text-gray-900 dark:text-gray-100 text-center", children: "Detalhes do Ingresso" }), _jsxs("div", { className: "space-y-2 text-sm", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Evento:" }), _jsx("span", { className: "font-medium text-gray-900 dark:text-gray-100", children: ticketData.eventTitle })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Tipo:" }), _jsx("span", { className: "font-medium text-gray-900 dark:text-gray-100", children: ticketData.ticketType })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Portador:" }), _jsx("span", { className: "font-medium text-gray-900 dark:text-gray-100", children: ticketData.holderName })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Data:" }), _jsx("span", { className: "font-medium text-gray-900 dark:text-gray-100", children: ticketData.eventDate })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { className: "text-gray-600 dark:text-gray-400", children: "Hor\u00E1rio:" }), _jsx("span", { className: "font-medium text-gray-900 dark:text-gray-100", children: ticketData.eventTime })] })] }), _jsx(Button, { className: "w-full mt-4", onClick: onConfirm, children: "\u2705 Confirmar Entrada" })] }))] }));
}
