import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
export function ValidatorForm({ ticketCode, setTicketCode, onSubmit, isValidating, onReset, userProfile, validationStatus, generateTestCode, createTestData, isCreatingTestData, }) {
    const allowedRoles = ["validator", "organizer", "admin"];
    const userRole = String(userProfile?.role || "user").toLowerCase();
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("form", { onSubmit: onSubmit, className: "space-y-6", "aria-busy": isValidating, children: [_jsxs("div", { children: [_jsx("label", { htmlFor: "ticketCode", className: "block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2", children: "C\u00F3digo do Ingresso" }), _jsxs("div", { className: "relative", children: [_jsx(Input, { id: "ticketCode", type: "text", value: ticketCode, onChange: (e) => setTicketCode(e.target.value), placeholder: "Ex: TICKET-1735210800000-ABC123", required: true, className: "pl-10 font-mono tracking-widest", disabled: isValidating, "aria-describedby": validationStatus
                                            ? "validation-help validation-result"
                                            : "validation-help" }), _jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx("span", { className: "text-muted-foreground", children: "\uD83C\uDFAB" }) })] }), _jsx("p", { id: "validation-help", className: "text-xs text-muted-foreground mt-2", children: "Exemplo: TICKET-1735210800000-ABC123" })] }), _jsxs("div", { className: "flex space-x-3", children: [_jsx(Button, { type: "submit", disabled: isValidating ||
                                    !ticketCode.trim() ||
                                    !allowedRoles.includes(userRole), className: "flex-1 flex justify-center items-center py-3 px-4 font-medium", children: isValidating ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" }), "Validando..."] })) : (_jsxs(_Fragment, { children: [_jsx("span", { className: "mr-2", children: "\uD83D\uDD0D" }), "Validar Ingresso"] })) }), _jsxs(Button, { type: "button", variant: "secondary", onClick: onReset, className: "px-4 py-3 font-medium", children: ["\uD83D\uDDD1\uFE0F", _jsx("span", { className: "sr-only", children: "Limpar c\u00F3digo" })] })] })] }), _jsxs("div", { className: "mt-6 p-4 rounded-lg bg-muted", children: [_jsx("h3", { className: "font-semibold text-foreground mb-3", children: "A\u00E7\u00F5es R\u00E1pidas" }), _jsxs("div", { className: "grid grid-cols-2 gap-3", children: [_jsxs(Button, { type: "button", onClick: generateTestCode, variant: "secondary", className: "py-2 px-3 text-sm", children: [_jsx("span", { className: "mr-1", children: "\uD83C\uDFB2" }), "C\u00F3digo Teste"] }), String(userProfile?.role || "user").toLowerCase() !== "user" && (_jsxs(Button, { type: "button", onClick: createTestData, disabled: isCreatingTestData, className: "py-2 px-3 text-sm", children: [_jsx("span", { className: "mr-1", children: "\uD83D\uDD27" }), isCreatingTestData ? "Criando..." : "Criar Dados"] }))] })] })] }));
}
