type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  userType: String!
  photoUrl: String
}

type Event @table {
  name: String!
  startDate: Timestamp!
  endDate: Timestamp!
  location: String!
  description: String!
  createdAt: Timestamp!
  organizer: User
  imageUrl: String
  maxAttendees: Int
}

type TicketType @table {
  name: String!
  price: Float!
  quantityAvailable: Int!
  createdAt: Timestamp!
  event: Event
  description: String
}

type Ticket @table {
  purchaseDate: Timestamp!
  qrCode: String!
  isUsed: Boolean!
  createdAt: Timestamp!
  attendee: User
  event: Event
  ticketType: TicketType
  transferToUser: User
}

type Order @table {
  orderDate: Timestamp!
  totalAmount: Float!
  paymentStatus: String!
  createdAt: Timestamp!
  attendee: User
  paymentGatewayTransactionId: String
}